// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.34.1
// source: packets.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkEncoding int32

const (
	ChunkEncoding_CHUNK_ENCODING_RAW ChunkEncoding = 0
	ChunkEncoding_CHUNK_ENCODING_RLE ChunkEncoding = 1
)

// Enum value maps for ChunkEncoding.
var (
	ChunkEncoding_name = map[int32]string{
		0: "CHUNK_ENCODING_RAW",
		1: "CHUNK_ENCODING_RLE",
	}
	ChunkEncoding_value = map[string]int32{
		"CHUNK_ENCODING_RAW": 0,
		"CHUNK_ENCODING_RLE": 1,
	}
)

func (x ChunkEncoding) Enum() *ChunkEncoding {
	p := new(ChunkEncoding)
	*p = x
	return p
}

func (x ChunkEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[0].Descriptor()
}

func (ChunkEncoding) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[0]
}

func (x ChunkEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkEncoding.Descriptor instead.
func (ChunkEncoding) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

type BlockAction_ActionType int32

const (
	BlockAction_DESTROY BlockAction_ActionType = 0
	BlockAction_PLACE   BlockAction_ActionType = 1
)

// Enum value maps for BlockAction_ActionType.
var (
	BlockAction_ActionType_name = map[int32]string{
		0: "DESTROY",
		1: "PLACE",
	}
	BlockAction_ActionType_value = map[string]int32{
		"DESTROY": 0,
		"PLACE":   1,
	}
)

func (x BlockAction_ActionType) Enum() *BlockAction_ActionType {
	p := new(BlockAction_ActionType)
	*p = x
	return p
}

func (x BlockAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[1].Descriptor()
}

func (BlockAction_ActionType) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[1]
}

func (x BlockAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockAction_ActionType.Descriptor instead.
func (BlockAction_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2, 0}
}

type ChunkData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Z int32 `protobuf:"varint,2,opt,name=z,proto3" json:"z,omitempty"`
	// Compacted block IDs or full array
	Blocks           []byte        `protobuf:"bytes,3,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Encoding         ChunkEncoding `protobuf:"varint,4,opt,name=encoding,proto3,enum=rumpelmc.api.ChunkEncoding" json:"encoding,omitempty"`
	UncompressedSize uint32        `protobuf:"varint,5,opt,name=uncompressed_size,json=uncompressedSize,proto3" json:"uncompressed_size,omitempty"`
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkData) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ChunkData) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *ChunkData) GetBlocks() []byte {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *ChunkData) GetEncoding() ChunkEncoding {
	if x != nil {
		return x.Encoding
	}
	return ChunkEncoding_CHUNK_ENCODING_RAW
}

func (x *ChunkData) GetUncompressedSize() uint32 {
	if x != nil {
		return x.UncompressedSize
	}
	return 0
}

type ClientPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *ClientPosition) Reset() {
	*x = ClientPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPosition) ProtoMessage() {}

func (x *ClientPosition) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPosition.ProtoReflect.Descriptor instead.
func (*ClientPosition) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *ClientPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClientPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClientPosition) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type BlockAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action  BlockAction_ActionType `protobuf:"varint,1,opt,name=action,proto3,enum=rumpelmc.api.BlockAction_ActionType" json:"action,omitempty"`
	X       int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y       int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Z       int32                  `protobuf:"varint,4,opt,name=z,proto3" json:"z,omitempty"`
	BlockId uint32                 `protobuf:"varint,5,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"` // Ignored for DESTROY
}

func (x *BlockAction) Reset() {
	*x = BlockAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAction) ProtoMessage() {}

func (x *BlockAction) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAction.ProtoReflect.Descriptor instead.
func (*BlockAction) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *BlockAction) GetAction() BlockAction_ActionType {
	if x != nil {
		return x.Action
	}
	return BlockAction_DESTROY
}

func (x *BlockAction) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BlockAction) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BlockAction) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *BlockAction) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

type InventorySlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId uint32 `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Count   uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *InventorySlot) Reset() {
	*x = InventorySlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventorySlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventorySlot) ProtoMessage() {}

func (x *InventorySlot) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventorySlot.ProtoReflect.Descriptor instead.
func (*InventorySlot) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *InventorySlot) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *InventorySlot) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type InventorySnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slots []*InventorySlot `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
}

func (x *InventorySnapshot) Reset() {
	*x = InventorySnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventorySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventorySnapshot) ProtoMessage() {}

func (x *InventorySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventorySnapshot.ProtoReflect.Descriptor instead.
func (*InventorySnapshot) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *InventorySnapshot) GetSlots() []*InventorySlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*Packet_Chunk
	//	*Packet_Position
	//	*Packet_BlockAction
	//	*Packet_InventorySnapshot
	Payload isPacket_Payload `protobuf_oneof:"payload"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (m *Packet) GetPayload() isPacket_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Packet) GetChunk() *ChunkData {
	if x, ok := x.GetPayload().(*Packet_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (x *Packet) GetPosition() *ClientPosition {
	if x, ok := x.GetPayload().(*Packet_Position); ok {
		return x.Position
	}
	return nil
}

func (x *Packet) GetBlockAction() *BlockAction {
	if x, ok := x.GetPayload().(*Packet_BlockAction); ok {
		return x.BlockAction
	}
	return nil
}

func (x *Packet) GetInventorySnapshot() *InventorySnapshot {
	if x, ok := x.GetPayload().(*Packet_InventorySnapshot); ok {
		return x.InventorySnapshot
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_Chunk struct {
	Chunk *ChunkData `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type Packet_Position struct {
	Position *ClientPosition `protobuf:"bytes,2,opt,name=position,proto3,oneof"`
}

type Packet_BlockAction struct {
	BlockAction *BlockAction `protobuf:"bytes,3,opt,name=block_action,json=blockAction,proto3,oneof"`
}

type Packet_InventorySnapshot struct {
	InventorySnapshot *InventorySnapshot `protobuf:"bytes,4,opt,name=inventory_snapshot,json=inventorySnapshot,proto3,oneof"`
}

func (*Packet_Chunk) isPacket_Payload() {}

func (*Packet_Position) isPacket_Payload() {}

func (*Packet_BlockAction) isPacket_Payload() {}

func (*Packet_InventorySnapshot) isPacket_Payload() {}

var File_packets_proto protoreflect.FileDescriptor

var file_packets_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x72, 0x75, 0x6d, 0x70, 0x65, 0x6c, 0x6d, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x22, 0xa5, 0x01,
	0x0a, 0x09, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x7a, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12,
	0x37, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x72, 0x75, 0x6d, 0x70, 0x65, 0x6c, 0x6d, 0x63, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x6e, 0x63, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x10, 0x75, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x64, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x3a, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x7a, 0x22, 0xb6, 0x01, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x3c, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x24, 0x2e, 0x72, 0x75, 0x6d, 0x70, 0x65, 0x6c, 0x6d, 0x63, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x7a, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x53, 0x54, 0x52, 0x4f, 0x59, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x01, 0x22, 0x40, 0x0a, 0x0d, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x11,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x72, 0x75, 0x6d, 0x70, 0x65, 0x6c, 0x6d, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73,
	0x6c, 0x6f, 0x74, 0x73, 0x22, 0x92, 0x02, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x2f, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x72, 0x75, 0x6d, 0x70, 0x65, 0x6c, 0x6d, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x3a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x75, 0x6d, 0x70, 0x65, 0x6c, 0x6d, 0x63, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x0c,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x75, 0x6d, 0x70, 0x65, 0x6c, 0x6d, 0x63, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x50, 0x0a, 0x12,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x75, 0x6d, 0x70, 0x65,
	0x6c, 0x6d, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x11, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x3f, 0x0a, 0x0d, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x48,
	0x55, 0x4e, 0x4b, 0x5f, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x41, 0x57,
	0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x48, 0x55, 0x4e, 0x4b, 0x5f, 0x45, 0x4e, 0x43, 0x4f,
	0x44, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x4c, 0x45, 0x10, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x72, 0x75,
	0x6d, 0x70, 0x65, 0x6c, 0x6d, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData = file_packets_proto_rawDesc
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(file_packets_proto_rawDescData)
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_packets_proto_goTypes = []any{
	(ChunkEncoding)(0),          // 0: rumpelmc.api.ChunkEncoding
	(BlockAction_ActionType)(0), // 1: rumpelmc.api.BlockAction.ActionType
	(*ChunkData)(nil),           // 2: rumpelmc.api.ChunkData
	(*ClientPosition)(nil),      // 3: rumpelmc.api.ClientPosition
	(*BlockAction)(nil),         // 4: rumpelmc.api.BlockAction
	(*InventorySlot)(nil),       // 5: rumpelmc.api.InventorySlot
	(*InventorySnapshot)(nil),   // 6: rumpelmc.api.InventorySnapshot
	(*Packet)(nil),              // 7: rumpelmc.api.Packet
}
var file_packets_proto_depIdxs = []int32{
	0, // 0: rumpelmc.api.ChunkData.encoding:type_name -> rumpelmc.api.ChunkEncoding
	1, // 1: rumpelmc.api.BlockAction.action:type_name -> rumpelmc.api.BlockAction.ActionType
	5, // 2: rumpelmc.api.InventorySnapshot.slots:type_name -> rumpelmc.api.InventorySlot
	2, // 3: rumpelmc.api.Packet.chunk:type_name -> rumpelmc.api.ChunkData
	3, // 4: rumpelmc.api.Packet.position:type_name -> rumpelmc.api.ClientPosition
	4, // 5: rumpelmc.api.Packet.block_action:type_name -> rumpelmc.api.BlockAction
	6, // 6: rumpelmc.api.Packet.inventory_snapshot:type_name -> rumpelmc.api.InventorySnapshot
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packets_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ChunkData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ClientPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BlockAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*InventorySlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*InventorySnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_packets_proto_msgTypes[5].OneofWrappers = []any{
		(*Packet_Chunk)(nil),
		(*Packet_Position)(nil),
		(*Packet_BlockAction)(nil),
		(*Packet_InventorySnapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packets_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		EnumInfos:         file_packets_proto_enumTypes,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_rawDesc = nil
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
