// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: packets.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockAction_ActionType int32

const (
	BlockAction_DESTROY BlockAction_ActionType = 0
	BlockAction_PLACE   BlockAction_ActionType = 1
)

// Enum value maps for BlockAction_ActionType.
var (
	BlockAction_ActionType_name = map[int32]string{
		0: "DESTROY",
		1: "PLACE",
	}
	BlockAction_ActionType_value = map[string]int32{
		"DESTROY": 0,
		"PLACE":   1,
	}
)

func (x BlockAction_ActionType) Enum() *BlockAction_ActionType {
	p := new(BlockAction_ActionType)
	*p = x
	return p
}

func (x BlockAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[0].Descriptor()
}

func (BlockAction_ActionType) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[0]
}

func (x BlockAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockAction_ActionType.Descriptor instead.
func (BlockAction_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2, 0}
}

type ChunkData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	X     int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Z     int32                  `protobuf:"varint,2,opt,name=z,proto3" json:"z,omitempty"`
	// Compacted block IDs or full array
	Blocks        []byte `protobuf:"bytes,3,opt,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkData) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ChunkData) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *ChunkData) GetBlocks() []byte {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type ClientPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPosition) Reset() {
	*x = ClientPosition{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPosition) ProtoMessage() {}

func (x *ClientPosition) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPosition.ProtoReflect.Descriptor instead.
func (*ClientPosition) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *ClientPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClientPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClientPosition) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type BlockAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        BlockAction_ActionType `protobuf:"varint,1,opt,name=action,proto3,enum=rumpelmc.api.BlockAction_ActionType" json:"action,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             int32                  `protobuf:"varint,4,opt,name=z,proto3" json:"z,omitempty"`
	BlockId       uint32                 `protobuf:"varint,5,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"` // Ignored for DESTROY
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockAction) Reset() {
	*x = BlockAction{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAction) ProtoMessage() {}

func (x *BlockAction) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAction.ProtoReflect.Descriptor instead.
func (*BlockAction) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *BlockAction) GetAction() BlockAction_ActionType {
	if x != nil {
		return x.Action
	}
	return BlockAction_DESTROY
}

func (x *BlockAction) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BlockAction) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BlockAction) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *BlockAction) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Packet_Chunk
	//	*Packet_Position
	//	*Packet_BlockAction
	Payload       isPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *Packet) GetPayload() isPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetChunk() *ChunkData {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *Packet) GetPosition() *ClientPosition {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Position); ok {
			return x.Position
		}
	}
	return nil
}

func (x *Packet) GetBlockAction() *BlockAction {
	if x != nil {
		if x, ok := x.Payload.(*Packet_BlockAction); ok {
			return x.BlockAction
		}
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_Chunk struct {
	Chunk *ChunkData `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type Packet_Position struct {
	Position *ClientPosition `protobuf:"bytes,2,opt,name=position,proto3,oneof"`
}

type Packet_BlockAction struct {
	BlockAction *BlockAction `protobuf:"bytes,3,opt,name=block_action,json=blockAction,proto3,oneof"`
}

func (*Packet_Chunk) isPacket_Payload() {}

func (*Packet_Position) isPacket_Payload() {}

func (*Packet_BlockAction) isPacket_Payload() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\frumpelmc.api\"?\n" +
	"\tChunkData\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01z\x18\x02 \x01(\x05R\x01z\x12\x16\n" +
	"\x06blocks\x18\x03 \x01(\fR\x06blocks\":\n" +
	"\x0eClientPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"\xb6\x01\n" +
	"\vBlockAction\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.rumpelmc.api.BlockAction.ActionTypeR\x06action\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x05R\x01z\x12\x19\n" +
	"\bblock_id\x18\x05 \x01(\rR\ablockId\"$\n" +
	"\n" +
	"ActionType\x12\v\n" +
	"\aDESTROY\x10\x00\x12\t\n" +
	"\x05PLACE\x10\x01\"\xc0\x01\n" +
	"\x06Packet\x12/\n" +
	"\x05chunk\x18\x01 \x01(\v2\x17.rumpelmc.api.ChunkDataH\x00R\x05chunk\x12:\n" +
	"\bposition\x18\x02 \x01(\v2\x1c.rumpelmc.api.ClientPositionH\x00R\bposition\x12>\n" +
	"\fblock_action\x18\x03 \x01(\v2\x19.rumpelmc.api.BlockActionH\x00R\vblockActionB\t\n" +
	"\apayloadB\x19Z\x17rumpelmc/server/pkg/apib\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packets_proto_goTypes = []any{
	(BlockAction_ActionType)(0), // 0: rumpelmc.api.BlockAction.ActionType
	(*ChunkData)(nil),           // 1: rumpelmc.api.ChunkData
	(*ClientPosition)(nil),      // 2: rumpelmc.api.ClientPosition
	(*BlockAction)(nil),         // 3: rumpelmc.api.BlockAction
	(*Packet)(nil),              // 4: rumpelmc.api.Packet
}
var file_packets_proto_depIdxs = []int32{
	0, // 0: rumpelmc.api.BlockAction.action:type_name -> rumpelmc.api.BlockAction.ActionType
	1, // 1: rumpelmc.api.Packet.chunk:type_name -> rumpelmc.api.ChunkData
	2, // 2: rumpelmc.api.Packet.position:type_name -> rumpelmc.api.ClientPosition
	3, // 3: rumpelmc.api.Packet.block_action:type_name -> rumpelmc.api.BlockAction
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[3].OneofWrappers = []any{
		(*Packet_Chunk)(nil),
		(*Packet_Position)(nil),
		(*Packet_BlockAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		EnumInfos:         file_packets_proto_enumTypes,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
