#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUT_DIR="${1:-"$ROOT_DIR/logs/gpu_single_edge_dirty_compare"}"

export RUMPELMC_EDGE_DIRTY_COMPARE_ACTION="${RUMPELMC_EDGE_DIRTY_COMPARE_ACTION:-toggle}"
export RUMPELMC_EDGE_DIRTY_COMPARE_X="${RUMPELMC_EDGE_DIRTY_COMPARE_X:-127}"
export RUMPELMC_EDGE_DIRTY_COMPARE_Y="${RUMPELMC_EDGE_DIRTY_COMPARE_Y:-64}"
export RUMPELMC_EDGE_DIRTY_COMPARE_Z="${RUMPELMC_EDGE_DIRTY_COMPARE_Z:-80}"
export RUMPELMC_EDGE_DIRTY_COMPARE_BLOCK_ID="${RUMPELMC_EDGE_DIRTY_COMPARE_BLOCK_ID:-1}"
export RUMPELMC_EDGE_DIRTY_COMPARE_EXPECTED_EDGES="${RUMPELMC_EDGE_DIRTY_COMPARE_EXPECTED_EDGES:-pos_x}"
export RUMPELMC_EDGE_DIRTY_COMPARE_EXPECTED_BOUNDS="${RUMPELMC_EDGE_DIRTY_COMPARE_EXPECTED_BOUNDS:-31,64,16:31,64,16}"

sh "$ROOT_DIR/scripts/gpu_terrain_edge_dirty_compare.sh" "$OUT_DIR"
