#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUT_DIR="${1:-"$ROOT_DIR/logs/gpu_single_edge_dirty_repeat"}"

export RUMPELMC_EDGE_DIRTY_REPEAT_COUNT="${RUMPELMC_EDGE_DIRTY_REPEAT_COUNT:-3}"
export RUMPELMC_EDGE_DIRTY_REPEAT_ACTION="${RUMPELMC_EDGE_DIRTY_REPEAT_ACTION:-toggle}"
export RUMPELMC_EDGE_DIRTY_REPEAT_X="${RUMPELMC_EDGE_DIRTY_REPEAT_X:-127}"
export RUMPELMC_EDGE_DIRTY_REPEAT_Y="${RUMPELMC_EDGE_DIRTY_REPEAT_Y:-64}"
export RUMPELMC_EDGE_DIRTY_REPEAT_Z="${RUMPELMC_EDGE_DIRTY_REPEAT_Z:-80}"
export RUMPELMC_EDGE_DIRTY_REPEAT_BLOCK_ID="${RUMPELMC_EDGE_DIRTY_REPEAT_BLOCK_ID:-1}"
export RUMPELMC_EDGE_DIRTY_REPEAT_EXPECTED_EDGES="${RUMPELMC_EDGE_DIRTY_REPEAT_EXPECTED_EDGES:-pos_x}"
export RUMPELMC_EDGE_DIRTY_REPEAT_EXPECTED_BOUNDS="${RUMPELMC_EDGE_DIRTY_REPEAT_EXPECTED_BOUNDS:-31,64,16:31,64,16}"
export RUMPELMC_EDGE_DIRTY_REPEAT_MIN_EDGE_NEIGHBOR_CHUNKS="${RUMPELMC_EDGE_DIRTY_REPEAT_MIN_EDGE_NEIGHBOR_CHUNKS:-2}"
export RUMPELMC_EDGE_DIRTY_REPEAT_MIN_EDGE_NEIGHBOR_SUBCHUNKS="${RUMPELMC_EDGE_DIRTY_REPEAT_MIN_EDGE_NEIGHBOR_SUBCHUNKS:-4}"
export RUMPELMC_EDGE_DIRTY_REPEAT_MIN_LAST_EDGE_NEIGHBOR_CHUNKS="${RUMPELMC_EDGE_DIRTY_REPEAT_MIN_LAST_EDGE_NEIGHBOR_CHUNKS:-1}"
export RUMPELMC_EDGE_DIRTY_REPEAT_MIN_LAST_EDGE_NEIGHBOR_SUBCHUNKS="${RUMPELMC_EDGE_DIRTY_REPEAT_MIN_LAST_EDGE_NEIGHBOR_SUBCHUNKS:-2}"

sh "$ROOT_DIR/scripts/gpu_terrain_edge_dirty_repeat.sh" "$OUT_DIR"
