#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUT_DIR="${1:-"$ROOT_DIR/logs/inventory_protocol_compatibility"}"
case "$OUT_DIR" in
  /*) ;;
  *) OUT_DIR="$ROOT_DIR/$OUT_DIR" ;;
esac

SUMMARY_PATH="$OUT_DIR/inventory-protocol-compatibility-summary.txt"
DESIGN_DOC="${RUMPELMC_INVENTORY_PROTOCOL_DOC:-"$ROOT_DIR/docs/INVENTORY_PROTOCOL_COMPATIBILITY.md"}"
PROTOCOL_DOC="${RUMPELMC_INVENTORY_PROTOCOL_MAIN_DOC:-"$ROOT_DIR/docs/PROTOCOL.md"}"
SERVER_INVENTORY_DOC="${RUMPELMC_INVENTORY_PROTOCOL_SERVER_INVENTORY_DOC:-"$ROOT_DIR/docs/SERVER_INVENTORY_FOUNDATION.md"}"
GAMEPLAY_DOC="${RUMPELMC_INVENTORY_PROTOCOL_GAMEPLAY_DOC:-"$ROOT_DIR/docs/GAMEPLAY_LOOP_FOUNDATION.md"}"
PROTO_SCHEMA="${RUMPELMC_INVENTORY_PROTOCOL_SCHEMA:-"$ROOT_DIR/api/schema/packets.proto"}"
GO_GENERATED="${RUMPELMC_INVENTORY_PROTOCOL_GO_GENERATED:-"$ROOT_DIR/server/pkg/api/packets.pb.go"}"
PROTOCOL_SUMMARY="${RUMPELMC_INVENTORY_PROTOCOL_DRIFT_SUMMARY:-"$ROOT_DIR/logs/protocol_generated_drift_current/protocol-generated-drift-summary.txt"}"
SERVER_INVENTORY_SUMMARY="${RUMPELMC_INVENTORY_PROTOCOL_SERVER_SUMMARY:-"$ROOT_DIR/logs/server_inventory_foundation_current/server-inventory-foundation-summary.txt"}"
GAMEPLAY_SUMMARY="${RUMPELMC_INVENTORY_PROTOCOL_GAMEPLAY_SUMMARY:-"$ROOT_DIR/logs/gameplay_loop_foundation_current/gameplay-loop-foundation-summary.txt"}"
RUN_PROTOCOL_GATE="${RUMPELMC_INVENTORY_PROTOCOL_RUN_PROTOCOL_GATE:-1}"
RUN_SERVER_INVENTORY_GATE="${RUMPELMC_INVENTORY_PROTOCOL_RUN_SERVER_GATE:-1}"
RUN_GAMEPLAY_GATE="${RUMPELMC_INVENTORY_PROTOCOL_RUN_GAMEPLAY_GATE:-1}"

mkdir -p "$OUT_DIR"

fail() {
  echo "inventory_protocol_compatibility_gate: $*" >&2
  exit 1
}

field_metric() {
  key="$1"
  path="$2"
  awk -v key="$key" '
    {
      prefix = key "="
      for (i = 1; i <= NF; i++) {
        if (index($i, prefix) == 1) {
          value = substr($i, length(prefix) + 1)
          gsub(/^"/, "", value)
          gsub(/"$/, "", value)
          print value
          exit
        }
      }
    }
  ' "$path"
}

require_token() {
  path="$1"
  token="$2"
  test -s "$path" || fail "missing file $path"
  grep -Fq "$token" "$path" || fail "missing token '$token' in $path"
}

for path in "$DESIGN_DOC" "$PROTOCOL_DOC" "$SERVER_INVENTORY_DOC" "$GAMEPLAY_DOC" "$PROTO_SCHEMA" "$GO_GENERATED"; do
  test -s "$path" || fail "missing required input $path"
done

for token in \
  'Inventory Protocol Compatibility' \
  'Current Decision' \
  'Current Wire Contract' \
  'Reserved Allocation' \
  'Compatibility Rules' \
  'inventory_protocol_status=compatibility_guarded' \
  '`Packet.block_action = 3`' \
  '`inventory_snapshot = 4`' \
  '`inventory_action = 5`' \
  'BlockAction` fields `1` through `5` stay fixed'; do
  require_token "$DESIGN_DOC" "$token"
done

require_token "$PROTOCOL_DOC" 'Inventory protocol compatibility planning lives in `docs/INVENTORY_PROTOCOL_COMPATIBILITY.md`.'
require_token "$PROTOCOL_DOC" '`Packet.block_action = 3`'
require_token "$SERVER_INVENTORY_DOC" 'Server Inventory Foundation'
require_token "$SERVER_INVENTORY_DOC" 'session-owned inventory'
require_token "$GAMEPLAY_DOC" 'Server Inventory Foundation'
require_token "$GAMEPLAY_DOC" 'server_inventory_status=session_guarded'
require_token "$PROTO_SCHEMA" 'message Packet'
require_token "$PROTO_SCHEMA" 'oneof payload'
require_token "$PROTO_SCHEMA" 'ChunkData chunk = 1;'
require_token "$PROTO_SCHEMA" 'ClientPosition position = 2;'
require_token "$PROTO_SCHEMA" 'BlockAction block_action = 3;'
require_token "$PROTO_SCHEMA" 'uint32 block_id = 5;'
require_token "$GO_GENERATED" 'Code generated by protoc-gen-go. DO NOT EDIT.'

if [ "$RUN_PROTOCOL_GATE" = "1" ]; then
  sh "$ROOT_DIR/scripts/protocol_generated_drift_gate.sh" "$ROOT_DIR/logs/protocol_generated_drift_current" > "$OUT_DIR/protocol-generated-drift-run.txt"
fi
if [ "$RUN_SERVER_INVENTORY_GATE" = "1" ]; then
  sh "$ROOT_DIR/scripts/server_inventory_foundation_gate.sh" "$ROOT_DIR/logs/server_inventory_foundation_current" > "$OUT_DIR/server-inventory-foundation-run.txt"
fi
if [ "$RUN_GAMEPLAY_GATE" = "1" ]; then
  sh "$ROOT_DIR/scripts/gameplay_loop_foundation_gate.sh" "$ROOT_DIR/logs/gameplay_loop_foundation_current" > "$OUT_DIR/gameplay-loop-foundation-run.txt"
fi

for path in "$PROTOCOL_SUMMARY" "$SERVER_INVENTORY_SUMMARY" "$GAMEPLAY_SUMMARY"; do
  test -s "$path" || fail "missing required summary $path"
done

protocol_status="$(field_metric status "$PROTOCOL_SUMMARY")"
protocol_schema_diff="$(field_metric schema_diff "$PROTOCOL_SUMMARY")"
protocol_generated_diff="$(field_metric generated_diff "$PROTOCOL_SUMMARY")"
server_inventory_status="$(field_metric status "$SERVER_INVENTORY_SUMMARY")"
server_inventory_guard="$(field_metric server_inventory_status "$SERVER_INVENTORY_SUMMARY")"
server_inventory_block_action="$(field_metric block_action_inventory "$SERVER_INVENTORY_SUMMARY")"
server_inventory_protocol_change="$(field_metric active_protocol_change "$SERVER_INVENTORY_SUMMARY")"
server_inventory_storage_change="$(field_metric active_storage_change "$SERVER_INVENTORY_SUMMARY")"
gameplay_status="$(field_metric status "$GAMEPLAY_SUMMARY")"
gameplay_inventory_guard="$(field_metric server_inventory_status "$GAMEPLAY_SUMMARY")"
gameplay_block_action_guard="$(field_metric server_inventory_block_action "$GAMEPLAY_SUMMARY")"
gameplay_protocol_change="$(field_metric active_protocol_change "$GAMEPLAY_SUMMARY")"

schema_diff_count="$(git -C "$ROOT_DIR" diff --name-only -- api/schema/packets.proto server/pkg/api/packets.pb.go | awk 'END { print NR + 0 }')"

awk \
  -v protocol_status="${protocol_status:-missing}" \
  -v protocol_schema_diff="${protocol_schema_diff:-1}" \
  -v protocol_generated_diff="${protocol_generated_diff:-1}" \
  -v server_inventory_status="${server_inventory_status:-missing}" \
  -v server_inventory_guard="${server_inventory_guard:-missing}" \
  -v server_inventory_block_action="${server_inventory_block_action:-missing}" \
  -v server_inventory_protocol_change="${server_inventory_protocol_change:-1}" \
  -v server_inventory_storage_change="${server_inventory_storage_change:-1}" \
  -v gameplay_status="${gameplay_status:-missing}" \
  -v gameplay_inventory_guard="${gameplay_inventory_guard:-missing}" \
  -v gameplay_block_action_guard="${gameplay_block_action_guard:-missing}" \
  -v gameplay_protocol_change="${gameplay_protocol_change:-1}" \
  -v schema_diff_count="$schema_diff_count" \
  -v design_doc="$DESIGN_DOC" \
  -v protocol_summary="$PROTOCOL_SUMMARY" \
  -v server_inventory_summary="$SERVER_INVENTORY_SUMMARY" \
  -v gameplay_summary="$GAMEPLAY_SUMMARY" '
  BEGIN {
    status = "pass"
    reason = "ok"
    inventory_protocol_status = "compatibility_guarded"
    current_wire_contract = "block_action_session_inventory"
    future_packet_tags = "packet_gt_3"
    future_block_action_fields = "block_action_gt_5"
    protocol_generated_drift = "guarded"
    server_inventory_report = server_inventory_guard
    gameplay_inventory_status = gameplay_inventory_guard

    protocol_ok = protocol_status == "pass" &&
      protocol_schema_diff + 0 == 0 &&
      protocol_generated_diff + 0 == 0
    server_ok = server_inventory_status == "pass" &&
      server_inventory_guard == "session_guarded" &&
      server_inventory_block_action == "session_guarded" &&
      server_inventory_protocol_change + 0 == 0 &&
      server_inventory_storage_change + 0 == 0
    gameplay_ok = gameplay_status == "pass" &&
      gameplay_inventory_guard == "session_guarded" &&
      gameplay_block_action_guard == "session_guarded" &&
      gameplay_protocol_change + 0 == 0

    if (schema_diff_count + 0 != 0) {
      status = "fail"
      reason = "schema_or_generated_diff_present"
    } else if (!protocol_ok) {
      status = "fail"
      reason = "protocol_drift_not_clean"
    } else if (!server_ok) {
      status = "fail"
      reason = "server_inventory_not_clean"
    } else if (!gameplay_ok) {
      status = "fail"
      reason = "gameplay_inventory_not_clean"
    }

    printf("inventory_protocol_compatibility status=%s reason=%s inventory_protocol_status=%s active_schema_change=%d current_wire_contract=%s future_packet_tags=%s future_block_action_fields=%s protocol_generated_drift=%s server_inventory_status=%s gameplay_inventory_status=%s protocol_summary=%s server_inventory_summary=%s gameplay_summary=%s design_doc=%s\n", status, reason, inventory_protocol_status, schema_diff_count, current_wire_contract, future_packet_tags, future_block_action_fields, protocol_generated_drift, server_inventory_report, gameplay_inventory_status, protocol_summary, server_inventory_summary, gameplay_summary, design_doc)
    if (status != "pass") {
      exit 1
    }
  }
' > "$SUMMARY_PATH" || {
  cat "$SUMMARY_PATH" >&2 || true
  fail "inventory protocol compatibility gate failed"
}

cat "$SUMMARY_PATH"
echo "Inventory protocol compatibility artifacts: $OUT_DIR"
