#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUT_DIR="${1:-"$ROOT_DIR/logs/protocol_generated_drift"}"
case "$OUT_DIR" in
  /*) ;;
  *) OUT_DIR="$ROOT_DIR/$OUT_DIR" ;;
esac

SUMMARY_PATH="$OUT_DIR/protocol-generated-drift-summary.txt"
PROTO_SCHEMA="${RUMPELMC_PROTOCOL_SCHEMA:-"$ROOT_DIR/api/schema/packets.proto"}"
GO_GENERATED="${RUMPELMC_PROTOCOL_GO_GENERATED:-"$ROOT_DIR/server/pkg/api/packets.pb.go"}"

mkdir -p "$OUT_DIR"

fail() {
  echo "protocol_generated_drift_gate: $*" >&2
  exit 1
}

require_token() {
  path="$1"
  token="$2"
  test -s "$path" || fail "missing file $path"
  grep -Fq "$token" "$path" || fail "missing token '$token' in $path"
}

require_token "$PROTO_SCHEMA" 'syntax = "proto3";'
require_token "$PROTO_SCHEMA" 'package rumpelmc.api;'
require_token "$PROTO_SCHEMA" 'option go_package = "rumpelmc/server/pkg/api";'
require_token "$PROTO_SCHEMA" 'message Packet'
require_token "$PROTO_SCHEMA" 'oneof payload'

require_token "$GO_GENERATED" 'Code generated by protoc-gen-go. DO NOT EDIT.'
require_token "$GO_GENERATED" 'source: packets.proto'
require_token "$GO_GENERATED" 'package api'
require_token "$GO_GENERATED" 'type Packet struct'
require_token "$GO_GENERATED" 'type ChunkData struct'

schema_diff_count="$(git -C "$ROOT_DIR" diff --name-only -- api/schema/packets.proto | awk 'END { print NR + 0 }')"
generated_diff_count="$(git -C "$ROOT_DIR" diff --name-only -- server/pkg/api/packets.pb.go | awk 'END { print NR + 0 }')"

awk \
  -v schema_diff_count="$schema_diff_count" \
  -v generated_diff_count="$generated_diff_count" \
  -v proto_schema="$PROTO_SCHEMA" \
  -v go_generated="$GO_GENERATED" '
  BEGIN {
    status = "pass"
    reason = "ok"
    generated_header = "guarded"
    schema_identity = "guarded"
    partial_generated_drift = "guarded"

    if ((schema_diff_count + 0 == 0 && generated_diff_count + 0 != 0) ||
        (schema_diff_count + 0 != 0 && generated_diff_count + 0 == 0)) {
      status = "fail"
      reason = "partial_schema_generated_diff"
    }

    printf("protocol_generated_drift status=%s reason=%s schema_diff=%d generated_diff=%d generated_header=%s schema_identity=%s partial_generated_drift=%s proto_schema=%s go_generated=%s\n", status, reason, schema_diff_count, generated_diff_count, generated_header, schema_identity, partial_generated_drift, proto_schema, go_generated)
    if (status != "pass") {
      exit 1
    }
  }
' > "$SUMMARY_PATH" || {
  cat "$SUMMARY_PATH" >&2 || true
  fail "protocol generated drift gate failed"
}

cat "$SUMMARY_PATH"
echo "Protocol generated drift artifacts: $OUT_DIR"
